/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.sbv.pjs.Modelo;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author bv1301144
 */
public class Background extends javax.swing.JPanel {

    /**
     * Creates new form Background
     */
    public Background() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/background.jpg"))); // NOI18N
        add(jLabel1, java.awt.BorderLayout.CENTER);
        BufferedImage img = null;
        try {
            URL urlImage = getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/background.png");
            System.out.println(urlImage);
            img = ImageIO.read(urlImage);
            Image icon = img.getScaledInstance(
                this.getWidth(),
                this.getHeight(),
                Image.SCALE_SMOOTH);
            this.setVisible(true);
            jLabel1.setIcon(new javax.swing.ImageIcon(icon)); // NOI18N
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
