/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.sbv.pjs.Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author bv1301268
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel_Codigo_CadastroFornecedor = new javax.swing.JLabel();
        jTextField_Codigo_Fornecedor = new javax.swing.JTextField();
        jLabel_CEP_CadastroFornecedor = new javax.swing.JLabel();
        jTextField_CEP_CadastroFornecedor = new javax.swing.JTextField();
        jLabel_OBS_CadastroFornecedor = new javax.swing.JLabel();
        jTextField_CNPJ_CadastroFornecedor = new javax.swing.JTextField();
        jLabel_Telefone_CadastroFornecedor = new javax.swing.JLabel();
        jTextField_Telefone_CadastroFornecedor = new javax.swing.JTextField();
        jLabel_Endereco_CadastroFornecedor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_Bairro_CadastroFornecedor = new javax.swing.JLabel();
        jTextField_Bairro_CadastroFornecedor = new javax.swing.JTextField();
        jLabel_Cidade_CadastroFornecedor = new javax.swing.JLabel();
        jTextField_Cidade_CadastroFornecedor = new javax.swing.JTextField();
        jLabel_Razao_Social_CadastroFornecedor = new javax.swing.JLabel();
        jTextField_Razao_Social_CadastroFornecedor = new javax.swing.JTextField();
        jLabel_CNPJ_CadastroFornecedor = new javax.swing.JLabel();
        jTextField_OBS_CadastroFornecedor = new javax.swing.JTextField();
        jButton_Salvar_CadastroFornecedor = new javax.swing.JButton();
        jButton_Editar_CadastroFornecedor = new javax.swing.JButton();
        jButton_Pesquisar_CadastroFornecedor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_Estado_CadastroFornecedor = new javax.swing.JComboBox();
        jTextField_Numero_CadastroFornecedor = new javax.swing.JTextField();
        jTextField_Endereco_CadastroFornecedor = new javax.swing.JTextField();
        jLabel_Celular_CadastroFornecedor = new javax.swing.JLabel();
        jTextField_Celular_CadastroFornecedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_CadastroFornecedor = new javax.swing.JTable();
        jButton_Pesquisar1 = new javax.swing.JButton();
        jButton_Limpar_CadastroFornecedor = new javax.swing.JButton();
        jButton_Excluir_CadastroFornecedor = new javax.swing.JButton();
        jButton_Sair_CadastroFornecedor = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1085, 623));

        jLayeredPane1.setToolTipText("");
        jLayeredPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1085, 623));

        jLabel_Codigo_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Codigo_CadastroFornecedor.setText("Codigo:");

        jTextField_Codigo_Fornecedor.setPreferredSize(new java.awt.Dimension(28, 20));

        jLabel_CEP_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_CEP_CadastroFornecedor.setText("CEP:");

        jTextField_CEP_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CEP_CadastroFornecedorActionPerformed(evt);
            }
        });

        jLabel_OBS_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_OBS_CadastroFornecedor.setText("Email:");

        jLabel_Telefone_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Telefone_CadastroFornecedor.setText("Telefone:");

        jTextField_Telefone_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Telefone_CadastroFornecedorActionPerformed(evt);
            }
        });

        jLabel_Endereco_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Endereco_CadastroFornecedor.setText("Endereço :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nº:");

        jLabel_Bairro_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Bairro_CadastroFornecedor.setText("Bairro :");

        jLabel_Cidade_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Cidade_CadastroFornecedor.setText("Cidade :");

        jTextField_Cidade_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cidade_CadastroFornecedorActionPerformed(evt);
            }
        });

        jLabel_Razao_Social_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Razao_Social_CadastroFornecedor.setText("Razão Social:");

        jTextField_Razao_Social_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Razao_Social_CadastroFornecedorActionPerformed(evt);
            }
        });

        jLabel_CNPJ_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_CNPJ_CadastroFornecedor.setText("CNPJ:");

        jButton_Salvar_CadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Salvar.png"))); // NOI18N
        jButton_Salvar_CadastroFornecedor.setText("Salvar");
        jButton_Salvar_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Salvar_CadastroFornecedorActionPerformed(evt);
            }
        });

        jButton_Editar_CadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Editar.png"))); // NOI18N
        jButton_Editar_CadastroFornecedor.setText("Editar");

        jButton_Pesquisar_CadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/lupa24.png"))); // NOI18N
        jButton_Pesquisar_CadastroFornecedor.setText("Pesquisar");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("UF :");

        jComboBox_Estado_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_Estado_CadastroFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBox_Estado_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Estado_CadastroFornecedorActionPerformed(evt);
            }
        });

        jTextField_Numero_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Numero_CadastroFornecedorActionPerformed(evt);
            }
        });

        jTextField_Endereco_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Endereco_CadastroFornecedorActionPerformed(evt);
            }
        });

        jLabel_Celular_CadastroFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Celular_CadastroFornecedor.setText("Celular:");

        jTextField_Celular_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Celular_CadastroFornecedorActionPerformed(evt);
            }
        });

        jTable_CadastroFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "RAZAO SOCIAL", "CNPJ", "ENDERECO", "CIDADE", "TELEFONE", "CELULAR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_CadastroFornecedor.setRowHeight(45);
        jScrollPane1.setViewportView(jTable_CadastroFornecedor);
        if (jTable_CadastroFornecedor.getColumnModel().getColumnCount() > 0) {
            jTable_CadastroFornecedor.getColumnModel().getColumn(0).setResizable(false);
            jTable_CadastroFornecedor.getColumnModel().getColumn(1).setResizable(false);
            jTable_CadastroFornecedor.getColumnModel().getColumn(2).setResizable(false);
            jTable_CadastroFornecedor.getColumnModel().getColumn(3).setResizable(false);
            jTable_CadastroFornecedor.getColumnModel().getColumn(4).setResizable(false);
            jTable_CadastroFornecedor.getColumnModel().getColumn(5).setResizable(false);
            jTable_CadastroFornecedor.getColumnModel().getColumn(6).setResizable(false);
        }

        jButton_Pesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Pesquisar.png"))); // NOI18N
        jButton_Pesquisar1.setText("Pesquisar");

        jButton_Limpar_CadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Limpar.png"))); // NOI18N
        jButton_Limpar_CadastroFornecedor.setText("Limpar");

        jButton_Excluir_CadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Excluir.png"))); // NOI18N
        jButton_Excluir_CadastroFornecedor.setText("Excluir");

        jButton_Sair_CadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Sair.png"))); // NOI18N
        jButton_Sair_CadastroFornecedor.setText("Sair");
        jButton_Sair_CadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_CadastroFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton_Salvar_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_Limpar_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_Pesquisar_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_Editar_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_Excluir_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_Sair_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jButton_Pesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CEP_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Cidade_CadastroFornecedor)
                                    .addComponent(jLabel_Codigo_CadastroFornecedor))
                                .addGap(10, 10, 10)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(jTextField_Cidade_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel_Telefone_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Telefone_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_Celular_CadastroFornecedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_Celular_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                                            .addComponent(jTextField_Codigo_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel_Razao_Social_CadastroFornecedor)
                                            .addGap(10, 10, 10)
                                            .addComponent(jTextField_Razao_Social_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel_CNPJ_CadastroFornecedor)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_CNPJ_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel_OBS_CadastroFornecedor)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField_OBS_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                            .addComponent(jTextField_CEP_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel_Endereco_CadastroFornecedor)
                                            .addGap(10, 10, 10)
                                            .addComponent(jTextField_Endereco_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel_Bairro_CadastroFornecedor)
                                            .addGap(10, 10, 10)
                                            .addComponent(jTextField_Bairro_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel6)
                                            .addGap(10, 10, 10)
                                            .addComponent(jTextField_Numero_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBox_Estado_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Codigo_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Codigo_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Razao_Social_CadastroFornecedor)
                    .addComponent(jTextField_Razao_Social_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CNPJ_CadastroFornecedor)
                    .addComponent(jTextField_CNPJ_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_OBS_CadastroFornecedor)
                    .addComponent(jTextField_OBS_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Bairro_CadastroFornecedor)
                    .addComponent(jTextField_Bairro_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Numero_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Estado_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CEP_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CEP_CadastroFornecedor)
                    .addComponent(jTextField_Endereco_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Endereco_CadastroFornecedor)
                    .addComponent(jLabel6))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Cidade_CadastroFornecedor)
                            .addComponent(jTextField_Cidade_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Celular_CadastroFornecedor)
                            .addComponent(jTextField_Celular_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Telefone_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Telefone_CadastroFornecedor))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Salvar_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Editar_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Pesquisar_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Limpar_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Excluir_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Sair_CadastroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addComponent(jButton_Pesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jLayeredPane1.setLayer(jLabel_Codigo_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Codigo_Fornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel_CEP_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_CEP_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel_OBS_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_CNPJ_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel_Telefone_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Telefone_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel_Endereco_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel_Bairro_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Bairro_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel_Cidade_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Cidade_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel_Razao_Social_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Razao_Social_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel_CNPJ_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_OBS_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_Salvar_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_Editar_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_Pesquisar_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBox_Estado_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Numero_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Endereco_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel_Celular_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Celular_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_Pesquisar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_Limpar_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_Excluir_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_Sair_CadastroFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
        );

        setBounds(224, 57, 1101, 661);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jTextField_Telefone_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Telefone_CadastroFornecedorActionPerformed
        buscaCep();
    }//GEN-LAST:event_jTextField_Telefone_CadastroFornecedorActionPerformed

    private void jComboBox_Estado_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Estado_CadastroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Estado_CadastroFornecedorActionPerformed

    private void jButton_Salvar_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar_CadastroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Salvar_CadastroFornecedorActionPerformed

    private void jTextField_Razao_Social_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Razao_Social_CadastroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Razao_Social_CadastroFornecedorActionPerformed

    private void jTextField_Cidade_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cidade_CadastroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cidade_CadastroFornecedorActionPerformed

    private void jTextField_Endereco_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Endereco_CadastroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Endereco_CadastroFornecedorActionPerformed

    private void jTextField_CEP_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CEP_CadastroFornecedorActionPerformed
        buscaCep();
    }//GEN-LAST:event_jTextField_CEP_CadastroFornecedorActionPerformed

    private void jTextField_Celular_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Celular_CadastroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Celular_CadastroFornecedorActionPerformed

    private void jTextField_Numero_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Numero_CadastroFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Numero_CadastroFornecedorActionPerformed

    private void jButton_Sair_CadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_CadastroFornecedorActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_Sair_CadastroFornecedorActionPerformed

     public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(jTextField_CEP_CadastroFornecedor.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
           jTextField_Endereco_CadastroFornecedor.setText(webServiceCep.getLogradouroFull());
           jTextField_Cidade_CadastroFornecedor.setText(webServiceCep.getCidade());
           jTextField_Bairro_CadastroFornecedor.setText(webServiceCep.getBairro());
           jComboBox_Estado_CadastroFornecedor.setSelectedItem(webServiceCep.getUf());
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Editar_CadastroFornecedor;
    private javax.swing.JButton jButton_Excluir_CadastroFornecedor;
    private javax.swing.JButton jButton_Limpar_CadastroFornecedor;
    private javax.swing.JButton jButton_Pesquisar1;
    private javax.swing.JButton jButton_Pesquisar_CadastroFornecedor;
    private javax.swing.JButton jButton_Sair_CadastroFornecedor;
    private javax.swing.JButton jButton_Salvar_CadastroFornecedor;
    private javax.swing.JComboBox jComboBox_Estado_CadastroFornecedor;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Bairro_CadastroFornecedor;
    private javax.swing.JLabel jLabel_CEP_CadastroFornecedor;
    private javax.swing.JLabel jLabel_CNPJ_CadastroFornecedor;
    private javax.swing.JLabel jLabel_Celular_CadastroFornecedor;
    private javax.swing.JLabel jLabel_Cidade_CadastroFornecedor;
    private javax.swing.JLabel jLabel_Codigo_CadastroFornecedor;
    private javax.swing.JLabel jLabel_Endereco_CadastroFornecedor;
    private javax.swing.JLabel jLabel_OBS_CadastroFornecedor;
    private javax.swing.JLabel jLabel_Razao_Social_CadastroFornecedor;
    private javax.swing.JLabel jLabel_Telefone_CadastroFornecedor;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_CadastroFornecedor;
    private javax.swing.JTextField jTextField_Bairro_CadastroFornecedor;
    private javax.swing.JTextField jTextField_CEP_CadastroFornecedor;
    private javax.swing.JTextField jTextField_CNPJ_CadastroFornecedor;
    private javax.swing.JTextField jTextField_Celular_CadastroFornecedor;
    private javax.swing.JTextField jTextField_Cidade_CadastroFornecedor;
    private javax.swing.JTextField jTextField_Codigo_Fornecedor;
    private javax.swing.JTextField jTextField_Endereco_CadastroFornecedor;
    private javax.swing.JTextField jTextField_Numero_CadastroFornecedor;
    private javax.swing.JTextField jTextField_OBS_CadastroFornecedor;
    private javax.swing.JTextField jTextField_Razao_Social_CadastroFornecedor;
    private javax.swing.JTextField jTextField_Telefone_CadastroFornecedor;
    // End of variables declaration//GEN-END:variables
}
