/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.sbv.pjs.Telas;

import java.awt.event.KeyEvent;

/**
 *
 * @author bv1301144
 */
public class CadastroNF extends javax.swing.JFrame {

    /**
     * Creates new form CadastroBoleto
     */
    public CadastroNF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Editar_CadastroNF = new javax.swing.JButton();
        jButton_Limpar_CadastroNF = new javax.swing.JButton();
        jButton_Pesquisar_CadastroNF = new javax.swing.JButton();
        jButton_Excluir_CadastroNF = new javax.swing.JButton();
        jButton_Salvar_CadastroNF = new javax.swing.JButton();
        jLabel_Total2_CadastroNF = new javax.swing.JLabel();
        jTextField_Codigo_CadastroNF = new javax.swing.JTextField();
        jLabel_Codigo_CadastroNF = new javax.swing.JLabel();
        jLabel_Produto_CadastroNF = new javax.swing.JLabel();
        jTextField_Produto_CadastroNF = new javax.swing.JTextField();
        jButton6_Pesquisar_Produto_CadastroNF = new javax.swing.JButton();
        jLabel_Qtde_CadastroNF = new javax.swing.JLabel();
        jTextField_Valor_CadastroNF = new javax.swing.JTextField();
        jLabel_Impostos_CadastroNF = new javax.swing.JLabel();
        jTextField_Impostos_CadastroNF = new javax.swing.JTextField();
        jLabel_Valor_CadastroNF = new javax.swing.JLabel();
        jTextField_qtde_CadastroNF = new javax.swing.JTextField();
        jLabel_QtdeParcela_CadastroNF = new javax.swing.JLabel();
        jTextField_Parcela2_CadastroNF = new javax.swing.JTextField();
        jLabel_Total1_CadastroNF = new javax.swing.JLabel();
        jTextField_Total_CadastroNF = new javax.swing.JTextField();
        jLabel_Emissao_CadastroNF = new javax.swing.JLabel();
        jLabel_Vencimento_CadastroNF = new javax.swing.JLabel();
        jLabel_NomeFantasia_CadastroNF = new javax.swing.JLabel();
        jTextField_NomeFantasia_CadastroNF = new javax.swing.JTextField();
        jLabel_RazaoSocial_CadastroNF = new javax.swing.JLabel();
        jTextField_RazaoSocial_CadastroNF = new javax.swing.JTextField();
        jLabel_NotaFiscal_CadastroNF = new javax.swing.JLabel();
        jLabel_CNPJ_CadastroNF = new javax.swing.JLabel();
        jTextField_CNPJ_CadastroNF = new javax.swing.JTextField();
        jTextField_NotaFiscal_CadastroNF = new javax.swing.JTextField();
        jButton7_Pesquisar_RazaoSocial_CadastroNF = new javax.swing.JButton();
        jDateChooser_Emissao_CadastroNF = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel_Total_CadastroNF = new javax.swing.JLabel();
        jLabel_QtdeParcela_CadastroNF1 = new javax.swing.JLabel();
        jTextField_Parcela1_CadastroNF = new javax.swing.JTextField();
        jTextField_Parcela3_CadastroNF = new javax.swing.JTextField();
        jLabel_Vencimento_CadastroNF1 = new javax.swing.JLabel();
        jLabel_Vencimento_CadastroNF2 = new javax.swing.JLabel();
        jTextField_Parcela4_CadastroNF = new javax.swing.JTextField();
        jTextField_Parcela5_CadastroNF = new javax.swing.JTextField();
        jLabel_Vencimento_CadastroNF3 = new javax.swing.JLabel();
        jTextField_Parcela6_CadastroNF = new javax.swing.JTextField();
        jButton_Sair_CadastroNF = new javax.swing.JButton();
        jButton1_OK_CadastroNF = new javax.swing.JButton();

        jButton_Editar_CadastroNF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Editar_CadastroNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Editar.png"))); // NOI18N
        jButton_Editar_CadastroNF.setText("Editar");

        jButton_Limpar_CadastroNF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Limpar_CadastroNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Limpar.png"))); // NOI18N
        jButton_Limpar_CadastroNF.setText("Limpar");
        jButton_Limpar_CadastroNF.setMaximumSize(new java.awt.Dimension(75, 25));
        jButton_Limpar_CadastroNF.setMinimumSize(new java.awt.Dimension(75, 25));

        jButton_Pesquisar_CadastroNF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Pesquisar_CadastroNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/lupa24.png"))); // NOI18N
        jButton_Pesquisar_CadastroNF.setText("Pesquisar");
        jButton_Pesquisar_CadastroNF.setMaximumSize(new java.awt.Dimension(75, 25));
        jButton_Pesquisar_CadastroNF.setMinimumSize(new java.awt.Dimension(75, 25));

        jButton_Excluir_CadastroNF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Excluir_CadastroNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Excluir.png"))); // NOI18N
        jButton_Excluir_CadastroNF.setText("Excluir");

        jButton_Salvar_CadastroNF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Salvar_CadastroNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Salvar.png"))); // NOI18N
        jButton_Salvar_CadastroNF.setText("Salvar");

        jLabel_Total2_CadastroNF.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_Total2_CadastroNF.setText("Total");

        jTextField_Codigo_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Codigo_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Codigo_CadastroNFKeyPressed(evt);
            }
        });

        jLabel_Codigo_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Codigo_CadastroNF.setText("Código:");

        jLabel_Produto_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Produto_CadastroNF.setText("Produto:");

        jTextField_Produto_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Produto_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Produto_CadastroNFKeyPressed(evt);
            }
        });

        jButton6_Pesquisar_Produto_CadastroNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/lupa16.png"))); // NOI18N

        jLabel_Qtde_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Qtde_CadastroNF.setText("Valor:");

        jTextField_Valor_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Valor_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Valor_CadastroNFKeyPressed(evt);
            }
        });

        jLabel_Impostos_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Impostos_CadastroNF.setText("Impostos:");

        jTextField_Impostos_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Impostos_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Impostos_CadastroNFKeyPressed(evt);
            }
        });

        jLabel_Valor_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Valor_CadastroNF.setText("Quantidade:");

        jTextField_qtde_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_qtde_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_qtde_CadastroNFKeyPressed(evt);
            }
        });

        jLabel_QtdeParcela_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_QtdeParcela_CadastroNF.setText("Parcelas 1:");

        jTextField_Parcela2_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Parcela2_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Parcela2_CadastroNFKeyPressed(evt);
            }
        });

        jLabel_Total1_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Total1_CadastroNF.setText("Total:");

        jTextField_Total_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_Emissao_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Emissao_CadastroNF.setText(" Emissão:");

        jLabel_Vencimento_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Vencimento_CadastroNF.setText("Parcela 3:");

        jLabel_NomeFantasia_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_NomeFantasia_CadastroNF.setText("Nome Fantasia:");

        jTextField_NomeFantasia_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_NomeFantasia_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_NomeFantasia_CadastroNFKeyPressed(evt);
            }
        });

        jLabel_RazaoSocial_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_RazaoSocial_CadastroNF.setText("Razão Social:");

        jTextField_RazaoSocial_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_RazaoSocial_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_RazaoSocial_CadastroNFKeyPressed(evt);
            }
        });

        jLabel_NotaFiscal_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_NotaFiscal_CadastroNF.setText("Nota Fiscal:");

        jLabel_CNPJ_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_CNPJ_CadastroNF.setText("CNPJ:");

        jTextField_CNPJ_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_CNPJ_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_CNPJ_CadastroNFKeyPressed(evt);
            }
        });

        jTextField_NotaFiscal_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_NotaFiscal_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_NotaFiscal_CadastroNFKeyPressed(evt);
            }
        });

        jButton7_Pesquisar_RazaoSocial_CadastroNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/lupa16.png"))); // NOI18N

        jDateChooser_Emissao_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooser_Emissao_CadastroNFKeyPressed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "codigo", "Produto", "Quantidade", "Valor Unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel_QtdeParcela_CadastroNF1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_QtdeParcela_CadastroNF1.setText("Parcelas 2:");

        jTextField_Parcela1_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Parcela1_CadastroNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Parcela1_CadastroNFActionPerformed(evt);
            }
        });
        jTextField_Parcela1_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Parcela1_CadastroNFKeyPressed(evt);
            }
        });

        jTextField_Parcela3_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Parcela3_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Parcela3_CadastroNFKeyPressed(evt);
            }
        });

        jLabel_Vencimento_CadastroNF1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Vencimento_CadastroNF1.setText("Parcela 6:");

        jLabel_Vencimento_CadastroNF2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Vencimento_CadastroNF2.setText("Parcela 4:");

        jTextField_Parcela4_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Parcela4_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Parcela4_CadastroNFKeyPressed(evt);
            }
        });

        jTextField_Parcela5_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Parcela5_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Parcela5_CadastroNFKeyPressed(evt);
            }
        });

        jLabel_Vencimento_CadastroNF3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Vencimento_CadastroNF3.setText("Parcela 5:");

        jTextField_Parcela6_CadastroNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Parcela6_CadastroNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Parcela6_CadastroNFKeyPressed(evt);
            }
        });

        jButton_Sair_CadastroNF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Sair_CadastroNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Sair.png"))); // NOI18N
        jButton_Sair_CadastroNF.setText("Sair");
        jButton_Sair_CadastroNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_CadastroNFActionPerformed(evt);
            }
        });

        jButton1_OK_CadastroNF.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton_Salvar_CadastroNF)
                                .addGap(15, 15, 15)
                                .addComponent(jButton_Editar_CadastroNF))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_QtdeParcela_CadastroNF)
                                    .addComponent(jLabel_Impostos_CadastroNF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_Impostos_CadastroNF)
                                    .addComponent(jTextField_Parcela1_CadastroNF, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_QtdeParcela_CadastroNF1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_Total1_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Parcela2_CadastroNF, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(jTextField_Total_CadastroNF))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_Vencimento_CadastroNF)
                                .addGap(10, 10, 10)
                                .addComponent(jTextField_Parcela3_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_Vencimento_CadastroNF2)
                                .addGap(10, 10, 10)
                                .addComponent(jTextField_Parcela4_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_Vencimento_CadastroNF3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton_Limpar_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jButton_Pesquisar_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jButton_Excluir_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jButton_Sair_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextField_Parcela5_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_Vencimento_CadastroNF1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Parcela6_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel_Total2_CadastroNF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_Total_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel_RazaoSocial_CadastroNF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_NotaFiscal_CadastroNF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                        .addComponent(jLabel_NomeFantasia_CadastroNF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel_Codigo_CadastroNF))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_NotaFiscal_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_CNPJ_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_CNPJ_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_RazaoSocial_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton7_Pesquisar_RazaoSocial_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jTextField_Codigo_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel_Produto_CadastroNF)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_Produto_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton6_Pesquisar_Produto_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel_Valor_CadastroNF)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_qtde_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel_Qtde_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_Valor_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton1_OK_CadastroNF))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jTextField_NomeFantasia_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel_Emissao_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jDateChooser_Emissao_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NotaFiscal_CadastroNF)
                    .addComponent(jLabel_CNPJ_CadastroNF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_CNPJ_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_NotaFiscal_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7_Pesquisar_RazaoSocial_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_RazaoSocial_CadastroNF)
                        .addComponent(jTextField_RazaoSocial_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_Emissao_CadastroNF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_NomeFantasia_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_NomeFantasia_CadastroNF)
                        .addComponent(jLabel_Emissao_CadastroNF)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6_Pesquisar_Produto_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_OK_CadastroNF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Codigo_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Codigo_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Produto_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_Produto_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Valor_CadastroNF)
                        .addComponent(jTextField_qtde_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Qtde_CadastroNF)
                        .addComponent(jTextField_Valor_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_QtdeParcela_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Parcela2_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_QtdeParcela_CadastroNF1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Parcela1_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Vencimento_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Vencimento_CadastroNF1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Parcela4_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Parcela5_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Vencimento_CadastroNF2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Vencimento_CadastroNF3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Parcela3_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Parcela6_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Impostos_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Impostos_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Total1_CadastroNF)
                            .addComponent(jTextField_Total_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Salvar_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Editar_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Limpar_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Pesquisar_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Excluir_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Sair_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Total2_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_Total_CadastroNF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        setBounds(224, 57, 1112, 662);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NotaFiscal_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NotaFiscal_CadastroNFKeyPressed
         if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_CNPJ_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_NotaFiscal_CadastroNFKeyPressed

    private void jTextField_CNPJ_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CNPJ_CadastroNFKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_RazaoSocial_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_CNPJ_CadastroNFKeyPressed

    private void jTextField_RazaoSocial_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_RazaoSocial_CadastroNFKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_NomeFantasia_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_RazaoSocial_CadastroNFKeyPressed

    private void jTextField_NomeFantasia_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NomeFantasia_CadastroNFKeyPressed
         if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jDateChooser_Emissao_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_NomeFantasia_CadastroNFKeyPressed

    private void jDateChooser_Emissao_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser_Emissao_CadastroNFKeyPressed
         if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Codigo_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jDateChooser_Emissao_CadastroNFKeyPressed

    private void jTextField_Codigo_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Codigo_CadastroNFKeyPressed
          if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Produto_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_Codigo_CadastroNFKeyPressed

    private void jTextField_Produto_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Produto_CadastroNFKeyPressed
           if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_qtde_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_Produto_CadastroNFKeyPressed

    private void jTextField_qtde_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_qtde_CadastroNFKeyPressed
            if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Valor_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_qtde_CadastroNFKeyPressed

    private void jTextField_Valor_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Valor_CadastroNFKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Parcela2_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_Valor_CadastroNFKeyPressed

    private void jTextField_Parcela2_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Parcela2_CadastroNFKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Parcela3_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_Parcela2_CadastroNFKeyPressed

    private void jTextField_Impostos_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Impostos_CadastroNFKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Total_CadastroNF.requestFocus();
     }
    }//GEN-LAST:event_jTextField_Impostos_CadastroNFKeyPressed

    private void jTextField_Parcela1_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Parcela1_CadastroNFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Parcela1_CadastroNFKeyPressed

    private void jTextField_Parcela3_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Parcela3_CadastroNFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Parcela3_CadastroNFKeyPressed

    private void jTextField_Parcela4_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Parcela4_CadastroNFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Parcela4_CadastroNFKeyPressed

    private void jTextField_Parcela5_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Parcela5_CadastroNFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Parcela5_CadastroNFKeyPressed

    private void jTextField_Parcela6_CadastroNFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Parcela6_CadastroNFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Parcela6_CadastroNFKeyPressed

    private void jTextField_Parcela1_CadastroNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Parcela1_CadastroNFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Parcela1_CadastroNFActionPerformed

    private void jButton_Sair_CadastroNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_CadastroNFActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_Sair_CadastroNFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroNF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroNF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_OK_CadastroNF;
    private javax.swing.JButton jButton6_Pesquisar_Produto_CadastroNF;
    private javax.swing.JButton jButton7_Pesquisar_RazaoSocial_CadastroNF;
    private javax.swing.JButton jButton_Editar_CadastroNF;
    private javax.swing.JButton jButton_Excluir_CadastroNF;
    private javax.swing.JButton jButton_Limpar_CadastroNF;
    private javax.swing.JButton jButton_Pesquisar_CadastroNF;
    private javax.swing.JButton jButton_Sair_CadastroNF;
    private javax.swing.JButton jButton_Salvar_CadastroNF;
    private com.toedter.calendar.JDateChooser jDateChooser_Emissao_CadastroNF;
    private javax.swing.JLabel jLabel_CNPJ_CadastroNF;
    private javax.swing.JLabel jLabel_Codigo_CadastroNF;
    private javax.swing.JLabel jLabel_Emissao_CadastroNF;
    private javax.swing.JLabel jLabel_Impostos_CadastroNF;
    private javax.swing.JLabel jLabel_NomeFantasia_CadastroNF;
    private javax.swing.JLabel jLabel_NotaFiscal_CadastroNF;
    private javax.swing.JLabel jLabel_Produto_CadastroNF;
    private javax.swing.JLabel jLabel_QtdeParcela_CadastroNF;
    private javax.swing.JLabel jLabel_QtdeParcela_CadastroNF1;
    private javax.swing.JLabel jLabel_Qtde_CadastroNF;
    private javax.swing.JLabel jLabel_RazaoSocial_CadastroNF;
    private javax.swing.JLabel jLabel_Total1_CadastroNF;
    private javax.swing.JLabel jLabel_Total2_CadastroNF;
    private javax.swing.JLabel jLabel_Total_CadastroNF;
    private javax.swing.JLabel jLabel_Valor_CadastroNF;
    private javax.swing.JLabel jLabel_Vencimento_CadastroNF;
    private javax.swing.JLabel jLabel_Vencimento_CadastroNF1;
    private javax.swing.JLabel jLabel_Vencimento_CadastroNF2;
    private javax.swing.JLabel jLabel_Vencimento_CadastroNF3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_CNPJ_CadastroNF;
    private javax.swing.JTextField jTextField_Codigo_CadastroNF;
    private javax.swing.JTextField jTextField_Impostos_CadastroNF;
    private javax.swing.JTextField jTextField_NomeFantasia_CadastroNF;
    private javax.swing.JTextField jTextField_NotaFiscal_CadastroNF;
    private javax.swing.JTextField jTextField_Parcela1_CadastroNF;
    private javax.swing.JTextField jTextField_Parcela2_CadastroNF;
    private javax.swing.JTextField jTextField_Parcela3_CadastroNF;
    private javax.swing.JTextField jTextField_Parcela4_CadastroNF;
    private javax.swing.JTextField jTextField_Parcela5_CadastroNF;
    private javax.swing.JTextField jTextField_Parcela6_CadastroNF;
    private javax.swing.JTextField jTextField_Produto_CadastroNF;
    private javax.swing.JTextField jTextField_RazaoSocial_CadastroNF;
    private javax.swing.JTextField jTextField_Total_CadastroNF;
    private javax.swing.JTextField jTextField_Valor_CadastroNF;
    private javax.swing.JTextField jTextField_qtde_CadastroNF;
    // End of variables declaration//GEN-END:variables
}
