/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.sbv.pjs.Telas;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author bv1301144
 */
public class CadastroClientes extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Nome_CadastroClientes = new javax.swing.JLabel();
        jTextField_Numero_CadastroClientes = new javax.swing.JTextField();
        jLabel_Endereco_CadastroClientes = new javax.swing.JLabel();
        jLabel_Telefone_CadastroClientes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Email_CadastroClientes = new javax.swing.JLabel();
        jTextField_Nome_CadastroClientes = new javax.swing.JTextField();
        jTextField_CEP_CadastroClientes = new javax.swing.JTextField();
        jTextField_Bairro_CadastroClientes = new javax.swing.JTextField();
        jLabel_CEP_CadastroClientes = new javax.swing.JLabel();
        jTextField_Email_CadastroClientes = new javax.swing.JTextField();
        jTextField_Endereco_CadastroClientes = new javax.swing.JTextField();
        jLabel_Numero_CadastroClientes = new javax.swing.JLabel();
        jLabel_Bairro_CadastroClientes = new javax.swing.JLabel();
        jTextField_Telefone_CadastroClientes = new javax.swing.JTextField();
        jLabel_Cidade_CadastroClientes = new javax.swing.JLabel();
        jTextField_Cidade_CadastroClientes = new javax.swing.JTextField();
        jLabel_UF_CadastroClientes = new javax.swing.JLabel();
        jButton_Salvar_CadastroClientes = new javax.swing.JButton();
        jButton_Limpar_CadastroClientes = new javax.swing.JButton();
        jButton_Editar_CadastroClientes = new javax.swing.JButton();
        jButton_Excluir_CadastroClientes = new javax.swing.JButton();
        jButton_Pesquisar_CadastroClientes = new javax.swing.JButton();
        jLabel_Codigo_CadastroClientes = new javax.swing.JLabel();
        jTextField_Codigo_CadastroClientes = new javax.swing.JTextField();
        jButton_Sair_CadastroClientes = new javax.swing.JButton();
        jComboBox_UF_CadastroClientes = new javax.swing.JComboBox();
        jLabel_CPF_CadastroClientes = new javax.swing.JLabel();
        jTextField_CPF_CadastroClientes = new javax.swing.JTextField();
        jLabel_Celular_CadastroClientes = new javax.swing.JLabel();
        jTextField_Celular_CadastroClientes = new javax.swing.JTextField();
        jLabel_TelefoneRecado_CadastroClientes = new javax.swing.JLabel();
        jTextField_TelefoneRecado_CadastroClientes = new javax.swing.JTextField();
        jLabel_OBS_CadastroClientes = new javax.swing.JLabel();
        jTextField_OBS_CadastroClientes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setTitle("Cadastro Clientes");
        setResizable(false);

        jLabel_Nome_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nome_CadastroClientes.setText("Nome:");

        jTextField_Numero_CadastroClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Numero_CadastroClientesKeyPressed(evt);
            }
        });

        jLabel_Endereco_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Endereco_CadastroClientes.setText("Endereco:");

        jLabel_Telefone_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Telefone_CadastroClientes.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_Email_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Email_CadastroClientes.setText("E-mail:");

        jTextField_Nome_CadastroClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Nome_CadastroClientesKeyPressed(evt);
            }
        });

        jTextField_CEP_CadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CEP_CadastroClientesActionPerformed(evt);
            }
        });
        jTextField_CEP_CadastroClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_CEP_CadastroClientesKeyPressed(evt);
            }
        });

        jTextField_Bairro_CadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Bairro_CadastroClientesActionPerformed(evt);
            }
        });

        jLabel_CEP_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_CEP_CadastroClientes.setText("Cep:");

        jLabel_Numero_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Numero_CadastroClientes.setText("Nº:");

        jLabel_Bairro_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Bairro_CadastroClientes.setText("Bairro:");

        jTextField_Telefone_CadastroClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Telefone_CadastroClientesKeyPressed(evt);
            }
        });

        jLabel_Cidade_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Cidade_CadastroClientes.setText("Cidade:");

        jLabel_UF_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_UF_CadastroClientes.setText("UF:");

        jButton_Salvar_CadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Salvar.png"))); // NOI18N
        jButton_Salvar_CadastroClientes.setText("Salvar");

        jButton_Limpar_CadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Limpar.png"))); // NOI18N
        jButton_Limpar_CadastroClientes.setText("Limpar");

        jButton_Editar_CadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Editar.png"))); // NOI18N
        jButton_Editar_CadastroClientes.setText("Editar");

        jButton_Excluir_CadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Excluir.png"))); // NOI18N
        jButton_Excluir_CadastroClientes.setText("Excluir");

        jButton_Pesquisar_CadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Pesquisar.png"))); // NOI18N
        jButton_Pesquisar_CadastroClientes.setText("Pesquisar");

        jLabel_Codigo_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Codigo_CadastroClientes.setText("Codigo:");

        jTextField_Codigo_CadastroClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Codigo_CadastroClientesKeyPressed(evt);
            }
        });

        jButton_Sair_CadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/sbv/pjs/Imagens/Sair.png"))); // NOI18N
        jButton_Sair_CadastroClientes.setText("Sair");
        jButton_Sair_CadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_CadastroClientesActionPerformed(evt);
            }
        });

        jComboBox_UF_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_UF_CadastroClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel_CPF_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_CPF_CadastroClientes.setText("CPF:");

        jLabel_Celular_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Celular_CadastroClientes.setText("Celular:");

        jLabel_TelefoneRecado_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_TelefoneRecado_CadastroClientes.setText("Telefone Recado:");

        jTextField_TelefoneRecado_CadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TelefoneRecado_CadastroClientesActionPerformed(evt);
            }
        });

        jLabel_OBS_CadastroClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_OBS_CadastroClientes.setText("OBS:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME", "ENDERECO", "BAIRRO", "TELEFONE", "CELULAR", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(45);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButton_Salvar_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Limpar_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton_Editar_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Excluir_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton_Sair_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Pesquisar_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_Telefone_CadastroClientes)
                                    .addComponent(jLabel_Bairro_CadastroClientes)
                                    .addComponent(jLabel_CEP_CadastroClientes)
                                    .addComponent(jLabel_Codigo_CadastroClientes))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_CEP_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_Endereco_CadastroClientes)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_Endereco_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField_Telefone_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel_Celular_CadastroClientes)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_Celular_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel_TelefoneRecado_CadastroClientes)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_TelefoneRecado_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel_Email_CadastroClientes)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_Email_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jTextField_Codigo_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(19, 19, 19)
                                                    .addComponent(jLabel_Nome_CadastroClientes)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField_Nome_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel_CPF_CadastroClientes)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextField_CPF_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(21, 21, 21)
                                                    .addComponent(jLabel_OBS_CadastroClientes))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jTextField_Bairro_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel_Cidade_CadastroClientes)
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jTextField_Cidade_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel_UF_CadastroClientes)
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboBox_UF_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Numero_CadastroClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Numero_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jTextField_OBS_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CPF_CadastroClientes)
                    .addComponent(jTextField_CPF_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Codigo_CadastroClientes)
                    .addComponent(jTextField_Codigo_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Nome_CadastroClientes)
                    .addComponent(jTextField_Nome_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_OBS_CadastroClientes)
                    .addComponent(jTextField_OBS_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CEP_CadastroClientes)
                    .addComponent(jTextField_CEP_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Endereco_CadastroClientes)
                    .addComponent(jTextField_Endereco_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Numero_CadastroClientes)
                    .addComponent(jTextField_Numero_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Cidade_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_UF_CadastroClientes)
                        .addComponent(jComboBox_UF_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Bairro_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Cidade_CadastroClientes)
                        .addComponent(jLabel_Bairro_CadastroClientes)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Celular_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Celular_CadastroClientes)
                    .addComponent(jTextField_Telefone_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Telefone_CadastroClientes)
                    .addComponent(jLabel_TelefoneRecado_CadastroClientes)
                    .addComponent(jTextField_TelefoneRecado_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Email_CadastroClientes)
                    .addComponent(jTextField_Email_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Salvar_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Limpar_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Editar_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Excluir_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Pesquisar_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Sair_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        setBounds(224, 57, 1101, 661);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_CEP_CadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CEP_CadastroClientesActionPerformed
     buscaCep();
    }//GEN-LAST:event_jTextField_CEP_CadastroClientesActionPerformed

    public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(jTextField_CEP_CadastroClientes.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
           jTextField_Endereco_CadastroClientes.setText(webServiceCep.getLogradouroFull());
           jTextField_Cidade_CadastroClientes.setText(webServiceCep.getCidade());
           jTextField_Bairro_CadastroClientes.setText(webServiceCep.getBairro());
           jComboBox_UF_CadastroClientes.setSelectedItem(webServiceCep.getUf());
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }

    private void jButton_Sair_CadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_CadastroClientesActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton_Sair_CadastroClientesActionPerformed

    private void jTextField_Codigo_CadastroClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Codigo_CadastroClientesKeyPressed
            if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Nome_CadastroClientes.requestFocus();
     }
    }//GEN-LAST:event_jTextField_Codigo_CadastroClientesKeyPressed

    private void jTextField_Nome_CadastroClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Nome_CadastroClientesKeyPressed
          if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_CEP_CadastroClientes.requestFocus();
     }
    }//GEN-LAST:event_jTextField_Nome_CadastroClientesKeyPressed

    private void jTextField_CEP_CadastroClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CEP_CadastroClientesKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Numero_CadastroClientes.requestFocus();
     }
    }//GEN-LAST:event_jTextField_CEP_CadastroClientesKeyPressed

    private void jTextField_Numero_CadastroClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Numero_CadastroClientesKeyPressed
    if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Telefone_CadastroClientes.requestFocus();
     }
    }//GEN-LAST:event_jTextField_Numero_CadastroClientesKeyPressed

    private void jTextField_Telefone_CadastroClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Telefone_CadastroClientesKeyPressed
                                                             
         if(evt.getKeyCode()== KeyEvent.VK_ENTER)
     {
         jTextField_Email_CadastroClientes.requestFocus();
     }
    }//GEN-LAST:event_jTextField_Telefone_CadastroClientesKeyPressed

    private void jTextField_TelefoneRecado_CadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TelefoneRecado_CadastroClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TelefoneRecado_CadastroClientesActionPerformed

    private void jTextField_Bairro_CadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Bairro_CadastroClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Bairro_CadastroClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Editar_CadastroClientes;
    private javax.swing.JButton jButton_Excluir_CadastroClientes;
    private javax.swing.JButton jButton_Limpar_CadastroClientes;
    private javax.swing.JButton jButton_Pesquisar_CadastroClientes;
    private javax.swing.JButton jButton_Sair_CadastroClientes;
    private javax.swing.JButton jButton_Salvar_CadastroClientes;
    private javax.swing.JComboBox jComboBox_UF_CadastroClientes;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Bairro_CadastroClientes;
    private javax.swing.JLabel jLabel_CEP_CadastroClientes;
    private javax.swing.JLabel jLabel_CPF_CadastroClientes;
    private javax.swing.JLabel jLabel_Celular_CadastroClientes;
    private javax.swing.JLabel jLabel_Cidade_CadastroClientes;
    private javax.swing.JLabel jLabel_Codigo_CadastroClientes;
    private javax.swing.JLabel jLabel_Email_CadastroClientes;
    private javax.swing.JLabel jLabel_Endereco_CadastroClientes;
    private javax.swing.JLabel jLabel_Nome_CadastroClientes;
    private javax.swing.JLabel jLabel_Numero_CadastroClientes;
    private javax.swing.JLabel jLabel_OBS_CadastroClientes;
    private javax.swing.JLabel jLabel_TelefoneRecado_CadastroClientes;
    private javax.swing.JLabel jLabel_Telefone_CadastroClientes;
    private javax.swing.JLabel jLabel_UF_CadastroClientes;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_Bairro_CadastroClientes;
    private javax.swing.JTextField jTextField_CEP_CadastroClientes;
    private javax.swing.JTextField jTextField_CPF_CadastroClientes;
    private javax.swing.JTextField jTextField_Celular_CadastroClientes;
    private javax.swing.JTextField jTextField_Cidade_CadastroClientes;
    private javax.swing.JTextField jTextField_Codigo_CadastroClientes;
    private javax.swing.JTextField jTextField_Email_CadastroClientes;
    private javax.swing.JTextField jTextField_Endereco_CadastroClientes;
    private javax.swing.JTextField jTextField_Nome_CadastroClientes;
    private javax.swing.JTextField jTextField_Numero_CadastroClientes;
    private javax.swing.JTextField jTextField_OBS_CadastroClientes;
    private javax.swing.JTextField jTextField_TelefoneRecado_CadastroClientes;
    private javax.swing.JTextField jTextField_Telefone_CadastroClientes;
    // End of variables declaration//GEN-END:variables
}
